WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/bin/python: can't open file 'downstream/train_protein_rna_inter.py': [Errno 2] No such file or directory
/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/bin/python: can't open file 'downstream/train_protein_rna_inter.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1634153) of binary: /home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/bin/python
Traceback (most recent call last):
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/bingxing2/ailab/scx6mh7/.conda/envs/dnalm_v2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
downstream/train_protein_rna_inter.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-30_20:50:03
  host      : paraai-n32-h-01-agent-101.paraai-n32-h-01.com
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 1634154)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-30_20:50:03
  host      : paraai-n32-h-01-agent-101.paraai-n32-h-01.com
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1634153)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
